name: hospital Backend Pipeline

on:
  push:
    branches:
      - master

jobs:
  Continues-Integration_build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: SamYoha99/hospital-backend
          ref: master

      - name: Build container image
        run: docker build -t docker.io/${{ secrets.DOCKER_USERNAME }}/hospital-app-backend:${{ github.run_number }} .

      - name: Log in to Docker Registry with short-lived credentials
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push image to Docker Registry
        run: docker push docker.io/${{ secrets.DOCKER_USERNAME }}/hospital-app-backend:${{ github.run_number }}

      - name: Clean up Docker image locally
        run: docker rmi docker.io/${{ secrets.DOCKER_USERNAME }}/hospital-app-backend:${{ github.run_number }}

      - name: Clean up GitHub repo on runner
        run: rm -rf ./*

  Continues-Deployment:
    runs-on: ubuntu-latest
    needs: Continues-Integration_build_and_push

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: SamYoha99/hospital-backend
          ref: master

      - name: Update Kubernetes Deployment file
        run: |
          sed -i "s+docker.io/${{ secrets.DOCKER_USERNAME }}/hospital-app-backend:.*+docker.io/${{ secrets.DOCKER_USERNAME }}/hospital-app-backend:${{ github.run_number }}+g" deployment/deploy.yaml

      - name: Authenticate to GCP and set up GKE
        run: |
          # Authenticate to GCP using the service account key
          echo "${{ secrets.GCP_SA_KEY }}" > $HOME/gcp-key.json
          export GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcp-key.json

          # Install dependencies and Google Cloud SDK
          sudo apt-get update
          sudo apt-get install -y apt-transport-https ca-certificates gnupg

          # Download and add the Google Cloud SDK GPG key
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo tee /usr/share/keyrings/cloud.google.gpg

          # Add Google Cloud SDK repository and install
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          sudo apt-get update
          sudo apt-get install -y google-cloud-sdk google-cloud-sdk-gke-gcloud-auth-plugin

          # Set the Google Cloud project and region/zone
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud config set compute/region ${{ secrets.GCP_COMPUTE_REGION }}
          gcloud config set compute/zone ${{ secrets.GCP_COMPUTE_ZONE }}

          # Get credentials for the GKE cluster using the auth plugin
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} --zone ${{ secrets.GCP_COMPUTE_ZONE }} --project ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy to GKE
        run: |
          # Apply Kubernetes configurations
          kubectl apply -f clusterissuer.yaml
          kubectl apply -f deployment/deploy.yaml

          # Sleep for 20 seconds to allow deployment to propagate
          sleep 20

          # Verify that the pod is running
          kubectl get pod
